### PR TITLE
Disable logging in Hashie::Mash subclasses while upgrading to version 3.5.2

### PR DESCRIPTION
**Pull request by zoras**
Fixes https://github.com/thekompanee/chamber/issues/49 by disabling logging via Mash subclasses to silence Hashie Warnings

https://github.com/intridea/hashie/blob/master/UPGRADING.md#upgrading-to-352

Why:

* Since the update to Hashie 3.5 the following warning is written to STDOUT when booting our Rails application:

```[bash]
❯ chamber secure
W, [2017-03-07T12:12:47.983000 #17933]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
...
W, [2017-03-07T12:12:55.025000 #17933]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
     encrypt  DEFAULT_MIXPANEL_MIXPANEL_TOKEN
     encrypt  DEMO_MIXPANEL_MIXPANEL_TOKEN
     encrypt  DEVELOPMENT_MIXPANEL_MIXPANEL_TOKEN
     encrypt  PRODUCTION_MIXPANEL_MIXPANEL_TOKEN
     encrypt  STAGING_MIXPANEL_MIXPANEL_TOKEN
     encrypt  TEST_MIXPANEL_MIXPANEL_TOKEN
W, [2017-03-07T12:12:55.068000 #17933]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
...
W, [2017-03-07T12:12:57.449000 #17933]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
❯ 
```
Read more at: intridea/hashie#394

### CODE REVIEW

**Comment by jfelchner** [comment]
@zoras I would prefer to actually fix the issue. I'm still unclear on what in chamber is causing the issue.

**Comment by zoras** [comment]
@jfelchner This is not a problem with chamber itself but a warning message from Hashie update. I'll update the pull request once Hashie v 3.5.2 is released with the ability to disable Hashie logs when there is a conflict between a key and a pre-existing method. 
See: https://github.com/intridea/hashie/commit/ba5854a8df89a5e930587622a74a5b188e9a5e06#diff-04c6e90faac2675aa89e2176d2eec7d8R534

**Comment by michaelherold** [comment]
I just released Hashie v3.5.2 which has the `disable_warnings` feature for the Mash logger and sets the Hashie logger to the Rails logger when we detect that we're running in Rails. Hopefully, this helps!

**Comment by jfelchner** [comment]
@michaelherold what specifically is the method that I'm calling that is throwing this warning?

**Comment by jfelchner** [comment]
Or the key that I'm setting

**Comment by michaelherold** [comment]
It says in your log that you're setting the `default` key (so either `"default"` or `:default`). This is colliding with the [Hash#default method](http://ruby-doc.org/core-2.4.0/Hash.html#method-i-default). This means that whenever you call `mash.default`, you will actually be getting the default for the hash, _not_ the value that you have set at the `default` key.

**Comment by mobilutz** [comment]
Would love to see this in the next release. And yes, a better way would be to find the real solution but that can be done later on, can't it?

**Comment by mobilutz** [comment]
Ok, I don't think that the `default` issue is a problem in Chamber. I had one YAML config named `default:` and renaming this made all the errors go away 😉 

Maybe there could be some kind of warning in Chamber that would say something like: `You are using a base function from Hash as a YAML key. You should change it`.

**Comment by jfelchner** [comment]
@mobilutz I actually like this solution much better.  _Much_ better.  We can output a warning if we see a key named `default` and actually explain what the problem is and ask them to simply rename it to `defaults` which should make all the warnings go away.

This will also require an update to the wiki pages which specifically call out `default` as the key to use (and probably why everyone is using it 😂)

Would someone be willing to PR this?

**Comment by jfelchner** [comment]
And just for the record, I've been reluctant to merge this particular PR because I don't like the solution at all.  It's a hack and I hate hacks :)

**Comment by jdickey** [comment]
@mobilutz You'd think that such conflicts would be caught by the language, or by static-analysis tools like RuboCop, but I vividly remember a *what's "sleep"?* weekend lost to tracking down just such a bug in my own code. The fix took all of five seconds; figuring out what *needed* fixing to make all the errors go away was a 30-hour journey down the encrusted rabbit hole.

*shudders violently*

**Comment by jfelchner** [comment]
@zoras FYI I removed the 9,000 useless duplicated lines from your issue because I got tired of scrolling past them.

**Comment by michaelherold** [comment]
FWIW, @mobilutz's suggestion is the whole purpose for this change in Hashie. People were constantly coming in with "it doesn't work" questions because they were trying to overwrite built-in methods. C'est la vie, I suppose ...

**Comment by jfelchner** [comment]
@michaelherold thanks for the clarification! 👍🏻

As I've mentioned, my ultimate plan is to completely remove Hashie as a dependency and just use bracket syntax. If I'm being honest, the only reason I added Hashie was to "compete" with the other gems that did similar things, but I think having no dependencies is a better selling point than being able to use dot syntax.

**Comment by jdickey** [comment]
@jfelchner 

>  having no dependencies is a better selling point than being able to use dot syntax

Not really disagreeing with that, but I find dot syntax pretty ruddy compelling. Have you ever looked at the [`dry-rb`](http://dry-rb.org) Gem `dry-struct`? ([docs](http://dry-rb.org/gems/dry-struct/), [repo](https://github.com/dry-rb/dry-struct)) We've been using it for several projects over the last few months, since it was in very early public release, and are absolutely thrilled with it; a worthy successor to Virtus.

**Comment by jfelchner** [comment]
@jdickey I'm a huge fan of anything solnic does. :)

Still not sure if I'm up for adding a dependency (especially one that has _additional_ dependencies) (_especially_ `ice_nine` which requires native C extensions) but I'll take a look.

Hopefully bracket syntax isn't so much of a deal breaker that you won't upgrade to Chamber `3.0` ;)

**Comment by michaelherold** [comment]
I'm 👍 on looking to remove Hashie. Even though I'm a maintainer of it, I would like to see more projects roll off of using it because I see it more as a prototyping gem than something that should be long-lived in a project.

If all you're really looking for is the dot syntax, you could make wrapper based on a recursive OpenStruct. It has roughly the same performance considerations as Hashie but wouldn't give all the niceties of being a Hash.

If you really do need a Hash and not a specific, then sticking with the bracket syntax is what I would do, FWIW.

**Comment by jfelchner** [comment]
For everyone on this thread, there is a super easy fix.  Just rename the `default` YAML key to `defaults`.

I am currently working on seeing what the impact is of ripping out `hashie`, but this issue has been sitting out here for a while and I know you all want a decent fix.

Thanks for the patience with this.

**Comment by jfelchner** [comment]
For reference, here's a [commit I made](https://github.com/thekompanee/chamber/commit/d163b69a1c1454ab7e5639cefe8af6516c9f3c15) to silence the warnings in the tests.

**Comment by jfelchner** [comment]
I'm going to close this for now since there is an easy fix for this and the warnings are, although annoying, valid and helpful.

I'll be updating the Wiki to change all the examples from using `default` keys to `defaults` keys.

**Pull request closed without merging**
